# replace default config

# multipass: true
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata: false
  - removeXMLNS
  - removeEditorsNSData
  - cleanupAttrs
  - inlineStyles
  - minifyStyles
  - convertStyleToAttrs
  - cleanupIDs: false
  - prefixIds
  - removeRasterImages
  - removeUselessDefs
  - cleanupNumericValues:
      floatPrecision: 1
  - cleanupListOfValues:
      floatPrecision: 1
  - convertColors
  - removeUnknownsAndDefaults: false
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill
  - removeViewBox
  - cleanupEnableBackground
  - removeHiddenElems: false
  - removeEmptyText
  - convertShapeToPath: false
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups
  - convertPathData:
      floatPrecision: 1
  - convertTransform:
      floatPrecision: 1
  - removeEmptyAttrs
  - removeEmptyContainers
  - mergePaths: false
  - removeUnusedNS
  - sortAttrs
  - removeTitle
  - removeDesc
  - removeDimensions
  - removeAttrs
  - removeElementsByAttr
  - addClassesToSVGElement
  - removeStyleElement
  - removeScriptElement
  - addAttributesToSVGElement

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
js2svg:
 pretty: true
 indent: '  '
