plugins:

  - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata: false
  - removeXMLNS
  - removeEditorsNSData
  - cleanupAttrs
  - inlineStyles
  - minifyStyles
  - convertStyleToAttrs
  - cleanupIDs: false
  - prefixIds
  - removeRasterImages
  - removeUselessDefs
  - cleanupNumericValues:
      floatPrecision: 1
  - cleanupListOfValues:
      floatPrecision: 1
  - convertColors
  - removeUnknownsAndDefaults: false
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill
  - removeViewBox
  - cleanupEnableBackground
  - removeHiddenElems: false
  - removeEmptyText
  - convertShapeToPath: false
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups
  - convertPathData:
      floatPrecision: 1
  - convertTransform:
      floatPrecision: 1
  - removeEmptyAttrs
  - removeEmptyContainers
  - mergePaths: false
  - removeUnusedNS
  - sortAttrs
  - removeTitle
  - removeDesc
  - removeDimensions
  - removeAttrs
  - removeElementsByAttr
  - addClassesToSVGElement
  - removeStyleElement
  - removeScriptElement
  - addAttributesToSVGElement

js2svg:
 pretty: true
 indent: '  '
